server.port=8000
springdoc.api-docs.path=/openapi.json
springdoc.api-docs.version=OPENAPI_3_0
server.compression.enabled=true
server.compression.min-response-size=1
server.compression.mime-types=application/json,text/plain
spring.jackson.datatype.datetime.write-dates-as-timestamps=false
