name: tonic_core
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  collection: ^1.19.1
  meta: ^1.16.0

dev_dependencies:
  build_runner: ^2.4.15
  test: ^1.24.0
  very_good_analysis: ^7.0.0
  
