name: immutable_collections_api
description: Generated API client for Immutable Collections Test API
version: 1.0.0
environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  big_decimal: ^0.7.0
  collection: ^1.17.0
  dio: ^5.8.0+1
  fast_immutable_collections: ^11.0.0
  meta: ^1.16.0
  tonik_util: ^0.6.0

dev_dependencies:
  lints: ^6.0.0

dependency_overrides:
  tonik_util:
    path: ../../../packages/tonik_util
