name: tonic

packages:
  - packages/**

scripts:
  generate:
    run: flutter pub run build_runner build --delete-conflicting-outputs
    exec:
      concurrency: 1
    select-package:
      depends-on: build_runner

command:
  bootstrap:
    usePubspecOverrides: true
    environment:
      sdk: ">=3.7.0 <4.0.0"
    dependencies:
      logging: ^1.3.0
      meta: ^1.16.0
    dev_dependencies:
      test: ^1.24.0
      very_good_analysis: ^6.0.0