name: tonic

packages:
  - packages/**

command:
  bootstrap:
    environment:
      sdk: ">=3.5.0 <4.0.0"
    dependencies:
      meta: ^1.16.0
    dev_dependencies:
      test: ^1.24.0
      very_good_analysis: ^6.0.0