name: tonik

packages:
  - packages/**

scripts:
  generate:
    run: flutter pub run build_runner build --delete-conflicting-outputs
    exec:
      concurrency: 1
    select-package:
      depends-on: build_runner

command:
  bootstrap:
    environment:
      sdk: ">=3.7.0 <4.0.0"
    dependencies:
      collection: ^1.19.1
      dart_style: ^3.0.1
      logging: ^1.3.0
      meta: ^1.16.0
      path: ^1.9.1
      spell_out_numbers: ^1.0.0
    dev_dependencies:
      test: ^1.24.0
      very_good_analysis: ^7.0.0