name: tonic_parse
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.5.0 <4.0.0"


dependencies:
  tonic_core:

dev_dependencies:
  very_good_analysis: ^6.0.0
  test: ^1.24.0
