name: tonic_parse
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  collection: ^1.19.1
  json_annotation: ^4.9.0
  logging: ^1.3.0
  tonic_core:

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.8.0
  test: ^1.24.0
  very_good_analysis: ^6.0.0
