name: tonic_generate
description: A code generation package for Tonic.
version: 1.0.0

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
    tonic_core:

dev_dependencies:
  test: ^1.24.0
  very_good_analysis: ^6.0.0
