name: tonic_generate
description: A code generation package for Tonic.
version: 1.0.0

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  change_case: ^2.2.0
  code_builder: ^4.10.0
  meta: ^1.16.0
  tonic_core:

dev_dependencies:
  test: ^1.24.0
  very_good_analysis: ^6.0.0
