source 'https://rubygems.org'
ruby '4.0.6'
gem 'rails', '8.1.3.1'
gem 'puma', '8.0.2'
gem 'rswag-api', '2.17.0'
gem 'rswag-specs', '2.17.0'
gem 'rspec-rails', '8.0.4'
# Rails and json-schema still use parsing options removed in JSON 3.
gem 'json', '2.21.2'
